name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install Dependencies
        env:
          USE_PRE: ${{ inputs.pre }}
        shell: bash
        run: |
          set -ux
          python -m pip install --upgrade pip
          if [ $USE_PRE ]; then
            pip install -Uq git+https://github.com/fastai/ghapi.git
            pip install -Uq git+https://github.com/fastai/fastcore.git
            pip install -Uq git+https://github.com/fastai/execnb.git
            pip install -Uq git+https://github.com/fastai/nbdev.git
            wget -q $(curl https://latest.fast.ai/pre/quarto-dev/quarto-cli/linux-amd64.deb)
            sudo dpkg -i quarto*.deb
          else
            pip install -Uq nbdev
          fi
          test -f setup.py && pip install -e ".[dev]"
          
      - name: Install nbdev-extensions
        run: pip install git+https://github.com/muellerzr/nbdev-extensions
        
      - name: Export notes
        run: parse_notes
      
      - name: Export docs
        run:  nbdev_docs

      - name: Enable GitHub Pages
        shell: python
        run: |
          import ghapi.core,nbdev.config,sys
          msg="Please enable GitHub Pages to publish from the root of the `gh-pages` branch per these instructions - https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-from-a-branch"
          try:
            api = ghapi.core.GhApi(owner=nbdev.config.get_config().user, repo=nbdev.config.get_config().repo, token="${{inputs.ghtoken}}")
            api.enable_pages(branch='gh-pages')
          except Exception as e: 
            print(f'::error title="Could not enable GitHub Pages Automatically":: {msg}\n{e}')
            sys.exit(1)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_dir: ./_docs
          # The following lines assign commit authorship to the official GH-Actions bot for deploys to `gh-pages` branch.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
      
